##### General #####
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
set -g history-limit 100000
set -g escape-time 0
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g automatic-rename off
set -g allow-rename off

##### Prefix / key bindings #####
# Change prefix from Ctrl-b to Ctrl-Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix
# Reload config quickly: Prefix + r
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

##### Splits #####
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}" 

# Vim-style pane movement (Alt + hjkl)
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Resize panes with Shift + hjkl
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Prefix + p → open centered popup at 90% size running your shell
unbind g
bind-key g display-popup -w 90% -h 90% -x C -y C -d "#{pane_current_path}" "$SHELL -i"

##### Mouse #####
set -g mouse on

##### Copy mode (vi-style) #####
setw -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi C-d send -X halfpage-down
bind -T copy-mode-vi C-u send -X halfpage-up

##### Status bar #####
set -g status-position top
set -g status-interval 15
set -g status-left-length 40
set -g status-right-length 80

# simple colors
set -g status-style "bg=black,fg=white"
set -g message-style "bg=black,fg=green"
set -g pane-border-style "fg=colour240"
set -g pane-active-border-style "fg=green"

# left/right status content
set -g status-left "#[fg=green]#S #[fg=white]| #[fg=yellow]#{user} "
set -g status-right "#{?window_zoomed_flag,#[fg=magenta][Z] #[fg=white]| ,}#[fg=green]#{battery_percentage} #[fg=white]| #[fg=yellow]%Y-%m-%d #[fg=white]| #[fg=cyan]%H:%M "

##### Window titles #####
setw -g window-status-current-style "fg=black,bg=yellow,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "

##### Kill pane without confirmantion #####
unbind x
bind x kill-pane

##### Plugins (TPM) #####
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-battery'

##### Continuum #####
set -g @continuum-save-interval '5'
set -g @continuum-restore 'on'

# Initialize TPM (keep this line at the bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
