#!/usr/bin/env python3
"""Generate kitty's light/dark color config from the vendored Catppuccin
palettes.

The palettes live in ./palettes and are in Ghostty's theme format: this repo
used to configure Ghostty too, and the generator existed to keep both terminals
byte-identical. Ghostty is gone, but the format is a plain 'key = value' list
that already parses, so it was kept rather than churned.

Run with no arguments to regenerate both themes in place.
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

# (palette file, human name, generated output)
THEMES = [
    ("catppuccin-latte.conf", "Catppuccin Latte", "light-theme.auto.conf"),
    ("catppuccin-macchiato.conf", "Catppuccin Macchiato", "dark-theme.auto.conf"),
]

def _lum(h):
    """WCAG relative luminance of #rrggbb."""
    c = []
    for i in (1, 3, 5):
        v = int(h[i:i + 2], 16) / 255
        c.append(v / 12.92 if v <= 0.04045 else ((v + 0.055) / 1.055) ** 2.4)
    return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]


def contrast(a, b):
    """WCAG contrast ratio between two #rrggbb colors."""
    la, lb = _lum(a), _lum(b)
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


def dim_but_legible(bg, candidates, floor=3.0):
    """Dimmest candidate still readable on bg; best-contrast one if none pass."""
    ok = [c for c in candidates if contrast(bg, c) >= floor]
    return min(ok, key=lambda c: contrast(bg, c)) if ok else \
        max(candidates, key=lambda c: contrast(bg, c))


SCALAR = {
    "background": "background",
    "foreground": "foreground",
    "cursor-color": "cursor",
    "cursor-text": "cursor_text_color",
    "selection-background": "selection_background",
    "selection-foreground": "selection_foreground",
}


def convert(src, name):
    colors = {}
    palette = {}
    for line in open(src):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, _, val = (p.strip() for p in line.partition("="))
        if key == "palette":
            idx, _, hexv = val.partition("=")
            palette[int(idx)] = hexv.strip()
        elif key in SCALAR:
            colors[SCALAR[key]] = val

    missing = [k for k in SCALAR.values() if k not in colors]
    if missing or sorted(palette) != list(range(16)):
        sys.exit(f"ERROR: {src}: missing {missing} or palette {sorted(palette)}")

    out = [
        f"# {name} — generated by generate-themes.py from palettes/. Regenerate",
        "# rather than hand-edit: the tab colors below are derived, not chosen.",
        "",
    ]
    for i in range(16):
        out.append(f"color{i:<21} {palette[i]}")
    out.append("")
    for k in ("background", "foreground",
              "selection_background", "selection_foreground"):
        out.append(f"{k:<26} {colors[k]}")
    out.append("")
    out.append("# 'none' means reverse video: the cursor takes the cell's own colors")
    out.append("# rather than a fixed one, so it stays visible over any background.")
    out.append(f"# (The palette's own cursor colour, {colors['cursor']}, is deliberately unused.)")
    out.append(f"{'cursor':<26} none")
    out.append("")
    bg = colors["background"]
    fg = colors["foreground"]
    # Dimmest palette colour that stays readable on this background: slot 8
    # suits light themes, but on dark ones it drops to ~2:1 contrast.
    inactive = dim_but_legible(bg, [palette[8], palette[7], fg])
    out.append("# Tab bar, derived from this palette. Neither tab gets a background")
    out.append("# fill — both sit on the window background so the whole bar stays")
    out.append("# uniformly translucent (kitty.conf sets tab_bar_background none, and")
    out.append("# a filled tab would render opaque against it). The active tab is")
    out.append("# marked by weight, not colour: bold (active_tab_font_style in")
    out.append("# kitty.conf) plus the full-strength foreground, versus the dimmed")
    out.append("# inactive foreground below.")
    out.append(f"# Foreground contrast on the bar: active {contrast(bg, fg):.1f}:1, "
               f"inactive {contrast(bg, inactive):.1f}:1.")
    out.append(f"{'active_tab_background':<26} {bg}")
    out.append(f"{'active_tab_foreground':<26} {fg}")
    out.append(f"{'inactive_tab_background':<26} {bg}")
    out.append(f"{'inactive_tab_foreground':<26} {inactive}")
    out.append("")
    return "\n".join(out)


if __name__ == "__main__":
    if len(sys.argv) != 1:
        sys.exit(f"usage: {sys.argv[0]}  (regenerates both themes in place)")
    for palette_file, name, dest in THEMES:
        out = convert(HERE / "palettes" / palette_file, name)
        (HERE / dest).write_text(out)
        print(f"wrote {dest}")
